version: '3.8'

services:
  backend:
    build:
      context: ./
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/flightbooking
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4.2
    container_name: flightbooking-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
